package a;

import android.view.ViewGroup;
import java.util.HashMap;

/* JADX INFO: loaded from: classes.dex */
public final class auc {

    /* JADX INFO: renamed from: a, reason: collision with root package name */
    public int f1376a;
    public String b;
    public final duc c;
    public final cuc d;
    public final buc e;
    public final euc f;
    public HashMap g;
    public ztc h;

    public auc() {
        duc ducVar = new duc();
        ducVar.f6248a = false;
        ducVar.b = 0;
        ducVar.c = 0;
        ducVar.d = 1.0f;
        ducVar.e = Float.NaN;
        this.c = ducVar;
        cuc cucVar = new cuc();
        cucVar.f4598a = false;
        cucVar.b = -1;
        cucVar.c = 0;
        cucVar.d = null;
        cucVar.e = -1;
        cucVar.f = 0;
        cucVar.g = Float.NaN;
        cucVar.h = Float.NaN;
        cucVar.i = Float.NaN;
        cucVar.j = -1;
        cucVar.k = null;
        cucVar.l = -3;
        cucVar.m = -1;
        this.d = cucVar;
        buc bucVar = new buc();
        bucVar.f2987a = false;
        bucVar.b = false;
        bucVar.e = -1;
        bucVar.f = -1;
        bucVar.g = -1.0f;
        bucVar.h = true;
        bucVar.i = -1;
        bucVar.j = -1;
        bucVar.k = -1;
        bucVar.l = -1;
        bucVar.m = -1;
        bucVar.n = -1;
        bucVar.o = -1;
        bucVar.p = -1;
        bucVar.q = -1;
        bucVar.r = -1;
        bucVar.s = -1;
        bucVar.t = -1;
        bucVar.u = -1;
        bucVar.v = -1;
        bucVar.w = -1;
        bucVar.x = 0.5f;
        bucVar.y = 0.5f;
        bucVar.z = null;
        bucVar.A = -1;
        bucVar.B = 0;
        bucVar.C = 0.0f;
        bucVar.D = -1;
        bucVar.E = -1;
        bucVar.F = -1;
        bucVar.G = 0;
        bucVar.H = 0;
        bucVar.I = 0;
        bucVar.J = 0;
        bucVar.K = 0;
        bucVar.L = 0;
        bucVar.M = 0;
        bucVar.N = Integer.MIN_VALUE;
        bucVar.O = Integer.MIN_VALUE;
        bucVar.P = Integer.MIN_VALUE;
        bucVar.Q = Integer.MIN_VALUE;
        bucVar.R = Integer.MIN_VALUE;
        bucVar.S = Integer.MIN_VALUE;
        bucVar.T = Integer.MIN_VALUE;
        bucVar.U = -1.0f;
        bucVar.V = -1.0f;
        bucVar.W = 0;
        bucVar.X = 0;
        bucVar.Y = 0;
        bucVar.Z = 0;
        bucVar.a0 = 0;
        bucVar.b0 = 0;
        bucVar.c0 = 0;
        bucVar.d0 = 0;
        bucVar.e0 = 1.0f;
        bucVar.f0 = 1.0f;
        bucVar.g0 = -1;
        bucVar.h0 = 0;
        bucVar.i0 = -1;
        bucVar.m0 = false;
        bucVar.n0 = false;
        bucVar.o0 = true;
        bucVar.p0 = 0;
        this.e = bucVar;
        euc eucVar = new euc();
        eucVar.f7870a = false;
        eucVar.b = 0.0f;
        eucVar.c = 0.0f;
        eucVar.d = 0.0f;
        eucVar.e = 1.0f;
        eucVar.f = 1.0f;
        eucVar.g = Float.NaN;
        eucVar.h = Float.NaN;
        eucVar.i = -1;
        eucVar.j = 0.0f;
        eucVar.k = 0.0f;
        eucVar.l = 0.0f;
        eucVar.m = false;
        eucVar.n = 0.0f;
        this.f = eucVar;
        this.g = new HashMap();
    }

    public static void a(auc aucVar, int i, ntc ntcVar) {
        aucVar.f1376a = i;
        buc bucVar = aucVar.e;
        bucVar.i = ntcVar.e;
        bucVar.j = ntcVar.f;
        bucVar.k = ntcVar.g;
        bucVar.l = ntcVar.h;
        bucVar.m = ntcVar.i;
        bucVar.n = ntcVar.j;
        bucVar.o = ntcVar.k;
        bucVar.p = ntcVar.l;
        bucVar.q = ntcVar.m;
        bucVar.r = ntcVar.n;
        bucVar.s = ntcVar.o;
        bucVar.t = ntcVar.s;
        bucVar.u = ntcVar.t;
        bucVar.v = ntcVar.u;
        bucVar.w = ntcVar.v;
        bucVar.x = ntcVar.E;
        bucVar.y = ntcVar.F;
        bucVar.z = ntcVar.G;
        bucVar.A = ntcVar.p;
        bucVar.B = ntcVar.q;
        bucVar.C = ntcVar.r;
        bucVar.D = ntcVar.T;
        bucVar.E = ntcVar.U;
        bucVar.F = ntcVar.V;
        bucVar.g = ntcVar.c;
        bucVar.e = ntcVar.f22368a;
        bucVar.f = ntcVar.b;
        bucVar.c = ((ViewGroup.MarginLayoutParams) ntcVar).width;
        bucVar.d = ((ViewGroup.MarginLayoutParams) ntcVar).height;
        bucVar.G = ((ViewGroup.MarginLayoutParams) ntcVar).leftMargin;
        bucVar.H = ((ViewGroup.MarginLayoutParams) ntcVar).rightMargin;
        bucVar.I = ((ViewGroup.MarginLayoutParams) ntcVar).topMargin;
        bucVar.J = ((ViewGroup.MarginLayoutParams) ntcVar).bottomMargin;
        bucVar.M = ntcVar.D;
        bucVar.U = ntcVar.I;
        bucVar.V = ntcVar.H;
        bucVar.X = ntcVar.K;
        bucVar.W = ntcVar.J;
        bucVar.m0 = ntcVar.W;
        bucVar.n0 = ntcVar.X;
        bucVar.Y = ntcVar.L;
        bucVar.Z = ntcVar.M;
        bucVar.a0 = ntcVar.P;
        bucVar.b0 = ntcVar.Q;
        bucVar.c0 = ntcVar.N;
        bucVar.d0 = ntcVar.O;
        bucVar.e0 = ntcVar.R;
        bucVar.f0 = ntcVar.S;
        bucVar.l0 = ntcVar.Y;
        bucVar.O = ntcVar.x;
        bucVar.Q = ntcVar.z;
        bucVar.N = ntcVar.w;
        bucVar.P = ntcVar.y;
        bucVar.S = ntcVar.A;
        bucVar.R = ntcVar.B;
        bucVar.T = ntcVar.C;
        bucVar.p0 = ntcVar.Z;
        bucVar.K = ntcVar.getMarginEnd();
        bucVar.L = ntcVar.getMarginStart();
    }

    public final void b(ntc ntcVar) {
        buc bucVar = this.e;
        ntcVar.e = bucVar.i;
        ntcVar.f = bucVar.j;
        ntcVar.g = bucVar.k;
        ntcVar.h = bucVar.l;
        ntcVar.i = bucVar.m;
        ntcVar.j = bucVar.n;
        ntcVar.k = bucVar.o;
        ntcVar.l = bucVar.p;
        ntcVar.m = bucVar.q;
        ntcVar.n = bucVar.r;
        ntcVar.o = bucVar.s;
        ntcVar.s = bucVar.t;
        ntcVar.t = bucVar.u;
        ntcVar.u = bucVar.v;
        ntcVar.v = bucVar.w;
        ((ViewGroup.MarginLayoutParams) ntcVar).leftMargin = bucVar.G;
        ((ViewGroup.MarginLayoutParams) ntcVar).rightMargin = bucVar.H;
        ((ViewGroup.MarginLayoutParams) ntcVar).topMargin = bucVar.I;
        ((ViewGroup.MarginLayoutParams) ntcVar).bottomMargin = bucVar.J;
        ntcVar.A = bucVar.S;
        ntcVar.B = bucVar.R;
        ntcVar.x = bucVar.O;
        ntcVar.z = bucVar.Q;
        ntcVar.E = bucVar.x;
        ntcVar.F = bucVar.y;
        ntcVar.p = bucVar.A;
        ntcVar.q = bucVar.B;
        ntcVar.r = bucVar.C;
        ntcVar.G = bucVar.z;
        ntcVar.T = bucVar.D;
        ntcVar.U = bucVar.E;
        ntcVar.I = bucVar.U;
        ntcVar.H = bucVar.V;
        ntcVar.K = bucVar.X;
        ntcVar.J = bucVar.W;
        ntcVar.W = bucVar.m0;
        ntcVar.X = bucVar.n0;
        ntcVar.L = bucVar.Y;
        ntcVar.M = bucVar.Z;
        ntcVar.P = bucVar.a0;
        ntcVar.Q = bucVar.b0;
        ntcVar.N = bucVar.c0;
        ntcVar.O = bucVar.d0;
        ntcVar.R = bucVar.e0;
        ntcVar.S = bucVar.f0;
        ntcVar.V = bucVar.F;
        ntcVar.c = bucVar.g;
        ntcVar.f22368a = bucVar.e;
        ntcVar.b = bucVar.f;
        ((ViewGroup.MarginLayoutParams) ntcVar).width = bucVar.c;
        ((ViewGroup.MarginLayoutParams) ntcVar).height = bucVar.d;
        String str = bucVar.l0;
        if (str != null) {
            ntcVar.Y = str;
        }
        ntcVar.Z = bucVar.p0;
        ntcVar.setMarginStart(bucVar.L);
        ntcVar.setMarginEnd(bucVar.K);
        ntcVar.a();
    }

    /* JADX INFO: renamed from: c, reason: merged with bridge method [inline-methods] */
    public final auc clone() {
        auc aucVar = new auc();
        aucVar.e.a(this.e);
        aucVar.d.a(this.d);
        duc ducVar = this.c;
        boolean z = ducVar.f6248a;
        duc ducVar2 = aucVar.c;
        ducVar2.f6248a = z;
        ducVar2.b = ducVar.b;
        ducVar2.d = ducVar.d;
        ducVar2.e = ducVar.e;
        ducVar2.c = ducVar.c;
        aucVar.f.a(this.f);
        aucVar.f1376a = this.f1376a;
        aucVar.h = this.h;
        return aucVar;
    }
}
