package a;

import java.util.List;

/* JADX INFO: loaded from: classes6.dex */
public abstract class dct {

    /* JADX INFO: renamed from: a, reason: collision with root package name */
    public static final List f5453a = avb.j("static/img/ImgDefault/Esports/Virtual/GoldRush/Bonuses/Bonus2.png", "static/img/ImgDefault/Esports/Virtual/GoldRush/Bonuses/Bonus1.png", "static/img/ImgDefault/Esports/Virtual/GoldRush/Bonuses/Bonus.png", "static/img/ImgDefault/Esports/Virtual/GoldRush/StatusBar/StateEnabled.png", "static/img/ImgDefault/Esports/Virtual/GoldRush/StatusBar/StateWinPlayer1.png", "static/img/ImgDefault/Esports/Virtual/GoldRush/StatusBar/StateWinPlayer2.png", "static/img/ImgDefault/Esports/Virtual/GoldRush/PlayersBoard/Player1.png", "static/img/ImgDefault/Esports/Virtual/GoldRush/PlayersBoard/Player1d.png", "static/img/ImgDefault/Esports/Virtual/GoldRush/PlayersBoard/Player2.png", "static/img/ImgDefault/Esports/Virtual/GoldRush/PlayersBoard/Player2d.png", "static/img/ImgDefault/Esports/Virtual/GoldRush/CircleForCube/Circle.png", "static/img/ImgDefault/Esports/Virtual/GoldRush/CircleForCube/CircleBlue.png", "static/img/ImgDefault/Esports/Virtual/GoldRush/CircleForCube/CirclePink.png", "static/img/ImgDefault/Esports/Virtual/GoldRush/Cube/State0.png", "static/img/ImgDefault/Esports/Virtual/GoldRush/Cube/State1.png", "static/img/ImgDefault/Esports/Virtual/GoldRush/Cube/State2.png", "static/img/ImgDefault/Esports/Virtual/GoldRush/Cube/State3.png", "static/img/ImgDefault/Esports/Virtual/GoldRush/Cube/State4.png", "static/img/ImgDefault/Esports/Virtual/GoldRush/Cube/State5.png", "static/img/ImgDefault/Esports/Virtual/GoldRush/Cube/State6.png", "static/img/ImgDefault/Esports/Virtual/GoldRush/PlayerIndicator/Player1.png", "static/img/ImgDefault/Esports/Virtual/GoldRush/PlayerIndicator/Player1Green.png", "static/img/ImgDefault/Esports/Virtual/GoldRush/PlayerIndicator/Player1Red.png", "static/img/ImgDefault/Esports/Virtual/GoldRush/PlayerIndicator/Player2.png", "static/img/ImgDefault/Esports/Virtual/GoldRush/PlayerIndicator/Player2Green.png", "static/img/ImgDefault/Esports/Virtual/GoldRush/PlayerIndicator/Player2Red.png", "static/img/ImgDefault/Esports/Virtual/GoldRush/PlayingField/Default/Fill.png", "static/img/ImgDefault/Esports/Virtual/GoldRush/PlayingField/Player1/Stroke.png", "static/img/ImgDefault/Esports/Virtual/GoldRush/PlayingField/Player1/Fill.png", "static/img/ImgDefault/Esports/Virtual/GoldRush/PlayingField/Player2/Stroke.png", "static/img/ImgDefault/Esports/Virtual/GoldRush/PlayingField/Player2/Fill.png", "static/img/ImgDefault/Esports/Virtual/GoldRush/Gold/IconGold.png", "static/img/ImgDefault/Esports/Virtual/GoldRush/PlayingField/Win/Fill.png", "static/img/ImgDefault/Esports/Virtual/GoldRush/PlayingField/Win/Stroke.png");
}
