package a;

import java.util.List;

/* JADX INFO: loaded from: classes3.dex */
public final class m1c {
    public final boolean A;
    public final boolean B;
    public final boolean C;
    public final boolean D;
    public final boolean E;
    public final boolean F;
    public final boolean G;
    public final boolean H;
    public final boolean I;
    public final boolean J;
    public final String K;
    public final String L;
    public final boolean M;
    public final List N;
    public final String O;
    public final String P;
    public final boolean Q;
    public final boolean R;
    public final boolean S;
    public final boolean T;
    public final boolean U;
    public final boolean V;
    public final boolean W;
    public final boolean X;
    public final boolean Y;
    public final boolean Z;

    /* JADX INFO: renamed from: a, reason: collision with root package name */
    public final int f19480a;
    public final boolean a0;
    public final String b;
    public final List b0;
    public final String c;
    public final boolean c0;
    public final List d;
    public final boolean d0;
    public final boolean e;
    public final boolean f;
    public final boolean g;
    public final boolean h;
    public final boolean i;
    public final boolean j;
    public final boolean k;
    public final boolean l;
    public final boolean m;
    public final String n;
    public final String o;
    public final String p;
    public final boolean q;
    public final boolean r;
    public final suu s;
    public final qjg0 t;
    public final int u;
    public final boolean v;
    public final boolean w;
    public final boolean x;
    public final boolean y;
    public final boolean z;

    public m1c(int i, String str, String str2, List list, boolean z, boolean z2, boolean z3, boolean z4, boolean z5, boolean z6, boolean z7, boolean z8, boolean z9, String str3, String str4, String str5, boolean z10, boolean z11, suu suuVar, qjg0 qjg0Var, int i2, boolean z12, boolean z13, boolean z14, boolean z15, boolean z16, boolean z17, boolean z18, boolean z19, boolean z20, boolean z21, boolean z22, boolean z23, boolean z24, boolean z25, boolean z26, String str6, String str7, boolean z27, List list2, String str8, String str9, boolean z28, boolean z29, boolean z30, boolean z31, boolean z32, boolean z33, boolean z34, boolean z35, boolean z36, boolean z37, boolean z38, List list3, boolean z39, boolean z40) {
        wuh.x(list, list2, list3);
        this.f19480a = i;
        this.b = str;
        this.c = str2;
        this.d = list;
        this.e = z;
        this.f = z2;
        this.g = z3;
        this.h = z4;
        this.i = z5;
        this.j = z6;
        this.k = z7;
        this.l = z8;
        this.m = z9;
        this.n = str3;
        this.o = str4;
        this.p = str5;
        this.q = z10;
        this.r = z11;
        this.s = suuVar;
        this.t = qjg0Var;
        this.u = i2;
        this.v = z12;
        this.w = z13;
        this.x = z14;
        this.y = z15;
        this.z = z16;
        this.A = z17;
        this.B = z18;
        this.C = z19;
        this.D = z20;
        this.E = z21;
        this.F = z22;
        this.G = z23;
        this.H = z24;
        this.I = z25;
        this.J = z26;
        this.K = str6;
        this.L = str7;
        this.M = z27;
        this.N = list2;
        this.O = str8;
        this.P = str9;
        this.Q = z28;
        this.R = z29;
        this.S = z30;
        this.T = z31;
        this.U = z32;
        this.V = z33;
        this.W = z34;
        this.X = z35;
        this.Y = z36;
        this.Z = z37;
        this.a0 = z38;
        this.b0 = list3;
        this.c0 = z39;
        this.d0 = z40;
    }
}
