package a;

import android.view.View;
import android.widget.ImageView;
import android.widget.TextView;
import org.xplatform.cyber.game.counterstrike.impl.presentation.statistic.tablet.Cs2StatisticTabletView;

/* JADX INFO: loaded from: classes3.dex */
public final class mbg implements c7q0 {
    public final ImageView A;
    public final TextView A0;
    public final ImageView B;
    public final TextView B0;
    public final ImageView C;
    public final View C0;
    public final ImageView D;
    public final View D0;
    public final ImageView E;
    public final View E0;
    public final ImageView F;
    public final View F0;
    public final ImageView G;
    public final View G0;
    public final ImageView H;
    public final View H0;
    public final ImageView I;
    public final ImageView J;
    public final ImageView K;
    public final TextView L;
    public final TextView M;
    public final TextView N;
    public final TextView O;
    public final TextView P;
    public final TextView Q;
    public final TextView R;
    public final TextView S;
    public final TextView T;
    public final TextView U;
    public final TextView V;
    public final TextView W;
    public final TextView X;
    public final TextView Y;
    public final TextView Z;

    /* JADX INFO: renamed from: a, reason: collision with root package name */
    public final Cs2StatisticTabletView f19974a;
    public final TextView a0;
    public final ImageView b;
    public final TextView b0;
    public final ImageView c;
    public final TextView c0;
    public final ImageView d;
    public final TextView d0;
    public final ImageView e;
    public final TextView e0;
    public final ImageView f;
    public final TextView f0;
    public final ImageView g;
    public final TextView g0;
    public final ImageView h;
    public final TextView h0;
    public final ImageView i;
    public final TextView i0;
    public final ImageView j;
    public final TextView j0;
    public final ImageView k;
    public final TextView k0;
    public final ImageView l;
    public final TextView l0;
    public final ImageView m;
    public final TextView m0;
    public final ImageView n;
    public final TextView n0;
    public final ImageView o;
    public final TextView o0;
    public final ImageView p;
    public final TextView p0;
    public final ImageView q;
    public final TextView q0;
    public final ImageView r;
    public final TextView r0;
    public final ImageView s;
    public final TextView s0;
    public final ImageView t;
    public final TextView t0;
    public final ImageView u;
    public final TextView u0;
    public final ImageView v;
    public final TextView v0;
    public final ImageView w;
    public final TextView w0;
    public final ImageView x;
    public final TextView x0;
    public final ImageView y;
    public final TextView y0;
    public final ImageView z;
    public final TextView z0;

    public mbg(Cs2StatisticTabletView cs2StatisticTabletView, ImageView imageView, ImageView imageView2, ImageView imageView3, ImageView imageView4, ImageView imageView5, ImageView imageView6, ImageView imageView7, ImageView imageView8, ImageView imageView9, ImageView imageView10, ImageView imageView11, ImageView imageView12, ImageView imageView13, ImageView imageView14, ImageView imageView15, ImageView imageView16, ImageView imageView17, ImageView imageView18, ImageView imageView19, ImageView imageView20, ImageView imageView21, ImageView imageView22, ImageView imageView23, ImageView imageView24, ImageView imageView25, ImageView imageView26, ImageView imageView27, ImageView imageView28, ImageView imageView29, ImageView imageView30, ImageView imageView31, ImageView imageView32, ImageView imageView33, ImageView imageView34, ImageView imageView35, ImageView imageView36, TextView textView, TextView textView2, TextView textView3, TextView textView4, TextView textView5, TextView textView6, TextView textView7, TextView textView8, TextView textView9, TextView textView10, TextView textView11, TextView textView12, TextView textView13, TextView textView14, TextView textView15, TextView textView16, TextView textView17, TextView textView18, TextView textView19, TextView textView20, TextView textView21, TextView textView22, TextView textView23, TextView textView24, TextView textView25, TextView textView26, TextView textView27, TextView textView28, TextView textView29, TextView textView30, TextView textView31, TextView textView32, TextView textView33, TextView textView34, TextView textView35, TextView textView36, TextView textView37, TextView textView38, TextView textView39, TextView textView40, TextView textView41, TextView textView42, TextView textView43, View view, View view2, View view3, View view4, View view5, View view6) {
        this.f19974a = cs2StatisticTabletView;
        this.b = imageView;
        this.c = imageView2;
        this.d = imageView3;
        this.e = imageView4;
        this.f = imageView5;
        this.g = imageView6;
        this.h = imageView7;
        this.i = imageView8;
        this.j = imageView9;
        this.k = imageView10;
        this.l = imageView11;
        this.m = imageView12;
        this.n = imageView13;
        this.o = imageView14;
        this.p = imageView15;
        this.q = imageView16;
        this.r = imageView17;
        this.s = imageView18;
        this.t = imageView19;
        this.u = imageView20;
        this.v = imageView21;
        this.w = imageView22;
        this.x = imageView23;
        this.y = imageView24;
        this.z = imageView25;
        this.A = imageView26;
        this.B = imageView27;
        this.C = imageView28;
        this.D = imageView29;
        this.E = imageView30;
        this.F = imageView31;
        this.G = imageView32;
        this.H = imageView33;
        this.I = imageView34;
        this.J = imageView35;
        this.K = imageView36;
        this.L = textView;
        this.M = textView2;
        this.N = textView3;
        this.O = textView4;
        this.P = textView5;
        this.Q = textView6;
        this.R = textView7;
        this.S = textView8;
        this.T = textView9;
        this.U = textView10;
        this.V = textView11;
        this.W = textView12;
        this.X = textView13;
        this.Y = textView14;
        this.Z = textView15;
        this.a0 = textView16;
        this.b0 = textView17;
        this.c0 = textView18;
        this.d0 = textView19;
        this.e0 = textView20;
        this.f0 = textView21;
        this.g0 = textView22;
        this.h0 = textView23;
        this.i0 = textView24;
        this.j0 = textView25;
        this.k0 = textView26;
        this.l0 = textView27;
        this.m0 = textView28;
        this.n0 = textView29;
        this.o0 = textView30;
        this.p0 = textView31;
        this.q0 = textView32;
        this.r0 = textView33;
        this.s0 = textView34;
        this.t0 = textView35;
        this.u0 = textView36;
        this.v0 = textView37;
        this.w0 = textView38;
        this.x0 = textView39;
        this.y0 = textView40;
        this.z0 = textView41;
        this.A0 = textView42;
        this.B0 = textView43;
        this.C0 = view;
        this.D0 = view2;
        this.E0 = view3;
        this.F0 = view4;
        this.G0 = view5;
        this.H0 = view6;
    }

    @Override // a.c7q0
    public final View getRoot() {
        return this.f19974a;
    }
}
