package a;

/* JADX INFO: loaded from: classes6.dex */
public abstract class ovb {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final long N;
    public static final long O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final long S;
    public static final long T;
    public static final long U;

    /* JADX INFO: renamed from: a, reason: collision with root package name */
    public static final long f24061a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    static {
        long j2 = wq50.o;
        f24061a = j2;
        b = wq50.c;
        c = wq50.d;
        d = wq50.m;
        long j3 = wq50.x;
        e = j3;
        f = wq50.h;
        long j4 = wq50.f;
        g = j4;
        h = wq50.b;
        i = wq50.f36789a;
        j = wq50.u;
        long j5 = wq50.t;
        k = j5;
        l = j5;
        m = wq50.v;
        n = wq50.A;
        long j6 = wq50.z;
        o = j6;
        p = j6;
        q = wq50.B;
        r = j4;
        s = wq50.p;
        t = wq50.G;
        long j7 = wq50.F;
        u = j7;
        v = j7;
        w = wq50.H;
        x = wq50.q;
        y = wq50.r;
        z = wq50.w;
        long j8 = wq50.y;
        A = j8;
        B = j8;
        C = j3;
        D = wq50.e;
        E = wq50.C;
        long j9 = wq50.E;
        F = j9;
        G = j9;
        H = wq50.D;
        I = j2;
        J = j2;
        K = wq50.l;
        L = wq50.k;
        M = wq50.j;
        N = wq50.n;
        O = wq50.g;
        P = wq50.i;
        Q = wq50.s;
        R = wq50.I;
        long j10 = wq50.K;
        S = j10;
        T = j10;
        U = wq50.J;
    }
}
