package a;

/* JADX INFO: loaded from: classes4.dex */
public final class rt80 {
    public final boolean A;
    public final boolean B;
    public final String C;
    public final String D;
    public final String E;
    public final int F;
    public final String G;
    public final String H;
    public final boolean I;
    public final ay9 J;
    public final long K;
    public final int L;
    public final int M;
    public final boolean N;
    public final String O;
    public final boolean P;
    public final int Q;
    public final boolean R;
    public final long S;
    public final String T;
    public final String U;
    public final String V;
    public final String W;
    public final String X;
    public final String Y;
    public final String Z;

    /* JADX INFO: renamed from: a, reason: collision with root package name */
    public final String f28833a;
    public final boolean a0;
    public final String b;
    public final boolean b0;
    public final String c;
    public final String c0;
    public final int d;
    public final String d0;
    public final String e;
    public final y0q0 e0;
    public final String f;
    public final String f0;
    public final int g;
    public final String g0;
    public final double h;
    public final String h0;
    public final double i;
    public final int i0;
    public final String j;
    public final boolean j0;
    public final hip0 k;
    public final double k0;
    public final boolean l;
    public final int l0;
    public final boolean m;
    public final boolean m0;
    public final boolean n;
    public final boolean n0;
    public final boolean o;
    public final boolean o0;
    public final String p;
    public final boolean p0;
    public final String q;
    public final boolean q0;
    public final String r;
    public final String r0;
    public final int s;
    public final boolean s0;
    public final String t;
    public final boolean t0;
    public final String u;
    public final String v;
    public final String w;
    public final String x;
    public final String y;
    public final String z;

    public rt80(String str, String str2, String str3, int i, String str4, String str5, int i2, double d, double d2, String str6, hip0 hip0Var, boolean z, boolean z2, boolean z3, boolean z4, String str7, String str8, String str9, int i3, String str10, String str11, String str12, String str13, String str14, String str15, String str16, boolean z5, boolean z6, String str17, String str18, String str19, int i4, String str20, String str21, boolean z7, ay9 ay9Var, long j, int i5, int i6, boolean z8, String str22, boolean z9, int i7, boolean z10, long j2, String str23, String str24, String str25, String str26, String str27, String str28, String str29, boolean z11, boolean z12, String str30, String str31, y0q0 y0q0Var, String str32, String str33, String str34, int i8, boolean z13, double d3, int i9, boolean z14, boolean z15, boolean z16, boolean z17, boolean z18, String str35, boolean z19, boolean z20) {
        this.f28833a = str;
        this.b = str2;
        this.c = str3;
        this.d = i;
        this.e = str4;
        this.f = str5;
        this.g = i2;
        this.h = d;
        this.i = d2;
        this.j = str6;
        this.k = hip0Var;
        this.l = z;
        this.m = z2;
        this.n = z3;
        this.o = z4;
        this.p = str7;
        this.q = str8;
        this.r = str9;
        this.s = i3;
        this.t = str10;
        this.u = str11;
        this.v = str12;
        this.w = str13;
        this.x = str14;
        this.y = str15;
        this.z = str16;
        this.A = z5;
        this.B = z6;
        this.C = str17;
        this.D = str18;
        this.E = str19;
        this.F = i4;
        this.G = str20;
        this.H = str21;
        this.I = z7;
        this.J = ay9Var;
        this.K = j;
        this.L = i5;
        this.M = i6;
        this.N = z8;
        this.O = str22;
        this.P = z9;
        this.Q = i7;
        this.R = z10;
        this.S = j2;
        this.T = str23;
        this.U = str24;
        this.V = str25;
        this.W = str26;
        this.X = str27;
        this.Y = str28;
        this.Z = str29;
        this.a0 = z11;
        this.b0 = z12;
        this.c0 = str30;
        this.d0 = str31;
        this.e0 = y0q0Var;
        this.f0 = str32;
        this.g0 = str33;
        this.h0 = str34;
        this.i0 = i8;
        this.j0 = z13;
        this.k0 = d3;
        this.l0 = i9;
        this.m0 = z14;
        this.n0 = z15;
        this.o0 = z16;
        this.p0 = z17;
        this.q0 = z18;
        this.r0 = str35;
        this.s0 = z19;
        this.t0 = z20;
    }

    public static rt80 a(rt80 rt80Var, ay9 ay9Var, int i, boolean z, int i2, int i3) {
        String str = rt80Var.f28833a;
        String str2 = rt80Var.b;
        String str3 = rt80Var.c;
        int i4 = rt80Var.d;
        String str4 = rt80Var.e;
        String str5 = rt80Var.f;
        int i5 = rt80Var.g;
        double d = rt80Var.h;
        double d2 = rt80Var.i;
        String str6 = rt80Var.j;
        hip0 hip0Var = rt80Var.k;
        boolean z2 = rt80Var.l;
        boolean z3 = rt80Var.m;
        boolean z4 = rt80Var.n;
        boolean z5 = rt80Var.o;
        String str7 = rt80Var.p;
        String str8 = rt80Var.q;
        String str9 = rt80Var.r;
        int i6 = rt80Var.s;
        String str10 = rt80Var.t;
        String str11 = rt80Var.u;
        String str12 = rt80Var.v;
        String str13 = rt80Var.w;
        String str14 = rt80Var.x;
        String str15 = rt80Var.y;
        String str16 = rt80Var.z;
        boolean z6 = rt80Var.A;
        boolean z7 = rt80Var.B;
        String str17 = rt80Var.C;
        String str18 = rt80Var.D;
        String str19 = rt80Var.E;
        int i7 = rt80Var.F;
        String str20 = rt80Var.G;
        String str21 = rt80Var.H;
        boolean z8 = rt80Var.I;
        ay9 ay9Var2 = (i2 & 8) != 0 ? rt80Var.J : ay9Var;
        long j = (i2 & 16) != 0 ? rt80Var.K : 0L;
        int i8 = (i2 & 32) != 0 ? rt80Var.L : i;
        int i9 = rt80Var.M;
        int i10 = i8;
        boolean z9 = rt80Var.N;
        String str22 = rt80Var.O;
        boolean z10 = rt80Var.P;
        int i11 = rt80Var.Q;
        boolean z11 = rt80Var.R;
        long j2 = rt80Var.S;
        String str23 = rt80Var.T;
        String str24 = rt80Var.U;
        String str25 = rt80Var.V;
        String str26 = rt80Var.W;
        String str27 = rt80Var.X;
        String str28 = rt80Var.Y;
        String str29 = rt80Var.Z;
        boolean z12 = (i2 & 1048576) != 0 ? rt80Var.a0 : false;
        boolean z13 = (i2 & 2097152) != 0 ? rt80Var.b0 : z;
        String str30 = rt80Var.c0;
        String str31 = rt80Var.d0;
        y0q0 y0q0Var = rt80Var.e0;
        String str32 = rt80Var.f0;
        String str33 = rt80Var.g0;
        String str34 = rt80Var.h0;
        int i12 = rt80Var.i0;
        boolean z14 = rt80Var.j0;
        double d3 = rt80Var.k0;
        int i13 = rt80Var.l0;
        boolean z15 = rt80Var.m0;
        boolean z16 = (i3 & 2) != 0 ? rt80Var.n0 : false;
        boolean z17 = rt80Var.o0;
        boolean z18 = rt80Var.p0;
        boolean z19 = rt80Var.q0;
        String str35 = rt80Var.r0;
        boolean z20 = rt80Var.s0;
        boolean z21 = rt80Var.t0;
        ay9Var2.getClass();
        return new rt80(str, str2, str3, i4, str4, str5, i5, d, d2, str6, hip0Var, z2, z3, z4, z5, str7, str8, str9, i6, str10, str11, str12, str13, str14, str15, str16, z6, z7, str17, str18, str19, i7, str20, str21, z8, ay9Var2, j, i10, i9, z9, str22, z10, i11, z11, j2, str23, str24, str25, str26, str27, str28, str29, z12, z13, str30, str31, y0q0Var, str32, str33, str34, i12, z14, d3, i13, z15, z16, z17, z18, z19, str35, z20, z21);
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof rt80)) {
            return false;
        }
        rt80 rt80Var = (rt80) obj;
        return this.f28833a.equals(rt80Var.f28833a) && this.b.equals(rt80Var.b) && this.c.equals(rt80Var.c) && this.d == rt80Var.d && this.e.equals(rt80Var.e) && this.f.equals(rt80Var.f) && this.g == rt80Var.g && Double.compare(this.h, rt80Var.h) == 0 && Double.compare(this.i, rt80Var.i) == 0 && this.j.equals(rt80Var.j) && this.k == rt80Var.k && this.l == rt80Var.l && this.m == rt80Var.m && this.n == rt80Var.n && this.o == rt80Var.o && this.p.equals(rt80Var.p) && this.q.equals(rt80Var.q) && this.r.equals(rt80Var.r) && this.s == rt80Var.s && this.t.equals(rt80Var.t) && this.u.equals(rt80Var.u) && this.v.equals(rt80Var.v) && this.w.equals(rt80Var.w) && this.x.equals(rt80Var.x) && this.y.equals(rt80Var.y) && this.z.equals(rt80Var.z) && this.A == rt80Var.A && this.B == rt80Var.B && this.C.equals(rt80Var.C) && this.D.equals(rt80Var.D) && this.E.equals(rt80Var.E) && this.F == rt80Var.F && this.G.equals(rt80Var.G) && this.H.equals(rt80Var.H) && this.I == rt80Var.I && this.J == rt80Var.J && this.K == rt80Var.K && this.L == rt80Var.L && this.M == rt80Var.M && this.N == rt80Var.N && this.O.equals(rt80Var.O) && this.P == rt80Var.P && this.Q == rt80Var.Q && this.R == rt80Var.R && this.S == rt80Var.S && this.T.equals(rt80Var.T) && this.U.equals(rt80Var.U) && this.V.equals(rt80Var.V) && this.W.equals(rt80Var.W) && this.X.equals(rt80Var.X) && this.Y.equals(rt80Var.Y) && this.Z.equals(rt80Var.Z) && this.a0 == rt80Var.a0 && this.b0 == rt80Var.b0 && this.c0.equals(rt80Var.c0) && this.d0.equals(rt80Var.d0) && this.e0 == rt80Var.e0 && this.f0.equals(rt80Var.f0) && this.g0.equals(rt80Var.g0) && this.h0.equals(rt80Var.h0) && this.i0 == rt80Var.i0 && this.j0 == rt80Var.j0 && Double.compare(this.k0, rt80Var.k0) == 0 && this.l0 == rt80Var.l0 && this.m0 == rt80Var.m0 && this.n0 == rt80Var.n0 && this.o0 == rt80Var.o0 && this.p0 == rt80Var.p0 && this.q0 == rt80Var.q0 && this.r0.equals(rt80Var.r0) && this.s0 == rt80Var.s0 && this.t0 == rt80Var.t0;
    }

    public final int hashCode() {
        return Boolean.hashCode(this.t0) + gtg0.e(ue30.b(gtg0.e(gtg0.e(gtg0.e(gtg0.e(gtg0.e(r8m.b(this.l0, mpn0.a(this.k0, gtg0.e(r8m.b(this.i0, ue30.b(ue30.b(ue30.b((this.e0.hashCode() + ue30.b(ue30.b(gtg0.e(gtg0.e(ue30.b(ue30.b(ue30.b(ue30.b(ue30.b(ue30.b(ue30.b(n22.b(gtg0.e(r8m.b(this.Q, gtg0.e(ue30.b(gtg0.e(r8m.b(this.M, r8m.b(this.L, n22.b((this.J.hashCode() + gtg0.e(ue30.b(ue30.b(r8m.b(this.F, ue30.b(ue30.b(ue30.b(gtg0.e(gtg0.e(ue30.b(ue30.b(ue30.b(ue30.b(ue30.b(ue30.b(ue30.b(r8m.b(this.s, ue30.b(ue30.b(ue30.b(gtg0.e(gtg0.e(gtg0.e(gtg0.e((this.k.hashCode() + ue30.b(mpn0.a(this.i, mpn0.a(this.h, r8m.b(this.g, ue30.b(ue30.b(r8m.b(this.d, ue30.b(ue30.b(this.f28833a.hashCode() * 31, 31, this.b), 31, this.c), 31), 31, this.e), 31, this.f), 31), 31), 31), 31, this.j)) * 31, 31, this.l), 31, this.m), 31, this.n), 31, this.o), 31, this.p), 31, this.q), 31, this.r), 31), 31, this.t), 31, this.u), 31, this.v), 31, this.w), 31, this.x), 31, this.y), 31, this.z), 31, this.A), 31, this.B), 31, this.C), 31, this.D), 31, this.E), 31), 31, this.G), 31, this.H), 31, this.I)) * 31, 31, this.K), 31), 31), 31, this.N), 31, this.O), 31, this.P), 31), 31, this.R), 31, this.S), 31, this.T), 31, this.U), 31, this.V), 31, this.W), 31, this.X), 31, this.Y), 31, this.Z), 31, this.a0), 31, this.b0), 31, this.c0), 31, this.d0)) * 31, 31, this.f0), 31, this.g0), 31, this.h0), 31), 31, this.j0), 31), 31), 31, this.m0), 31, this.n0), 31, this.o0), 31, this.p0), 31, this.q0), 31, this.r0), 31, this.s0);
    }

    public final String toString() {
        StringBuilder sbV = p39.v("ProfileInfo(middlename=", this.f28833a, ", birthday=", this.b, ", idCountry=");
        mpn0.A(sbV, this.d, this.c, ", idCity=", ", nameCountry=");
        asc.y(sbV, this.e, ", nameRegion=", this.f, ", regionId=");
        sbV.append(this.g);
        sbV.append(", timeZone=");
        sbV.append(this.h);
        vdd.z(sbV, ", money=", this.i, ", dateRegistration=");
        sbV.append(this.j);
        sbV.append(", activationType=");
        sbV.append(this.k);
        sbV.append(", sendMailInfo=");
        k5h.C(", sendMailBet=", ", sendSmsInfo=", sbV, this.l, this.m);
        k5h.C(", callBet=", ", skype=", sbV, this.n, this.o);
        asc.y(sbV, this.p, ", secure=", this.q, ", nick=");
        mpn0.A(sbV, this.s, this.r, ", sex=", ", birthPlace=");
        asc.y(sbV, this.t, ", addressRegistration=", this.u, ", workplace=");
        asc.y(sbV, this.v, ", passportSeries=", this.w, ", passport=");
        asc.y(sbV, this.x, ", passportDate=", this.y, ", passportIssuedBy=");
        gtg0.B(this.z, ", notifyDeposit=", ", agreeBonus=", sbV, this.A);
        jr0.z(", codeCountry=", this.C, ", birthdayText=", sbV, this.B);
        asc.y(sbV, this.D, ", passportDateText=", this.E, ", documentType=");
        ue30.u(sbV, this.F, ", documentName=", this.G, ", inn=");
        gtg0.B(this.H, ", isVip=", ", cashbackType=", sbV, this.I);
        sbV.append(this.J);
        sbV.append(", pointsAccumulated=");
        sbV.append(this.K);
        wuh.w(sbV, ", choiceBonus=", this.L, ", firstChoiceBonus=", this.M);
        vdd.t(", blockEmailAuthorization=", ", refUrl=", this.O, sbV, this.N);
        ue30.r(this.Q, ", hasBet=", ", partner=", sbV, this.P);
        qx4.B(sbV, ", isRegisterBonusExpired=", this.R, ", id=");
        mm7.u(this.S, ", email=", this.T, sbV);
        asc.y(sbV, ", name=", this.U, ", surname=", this.V);
        asc.y(sbV, ", nameCity=", this.W, ", cardNumber=", this.X);
        asc.y(sbV, ", fullCardNumber=", this.Y, ", phone=", this.Z);
        snr0.p(", twoFactor=", ", qrAuth=", sbV, this.a0, this.b0);
        asc.y(sbV, ", login=", this.c0, ", bankAccountNumber=", this.d0);
        sbV.append(", verificationStatus=");
        sbV.append(this.e0);
        sbV.append(", passportSubCode=");
        sbV.append(this.f0);
        asc.y(sbV, ", snils=", this.g0, ", nationality=", this.h0);
        p39.x(this.i0, ", changePassDaysPassed=", ", isMulticurrencyAvailable=", sbV, this.j0);
        vdd.z(sbV, ", userProfit=", this.k0, ", couponSize=");
        jr0.u(this.l0, ", testAccount=", ", hasAuthenticator=", sbV, this.m0);
        k5h.C(", allowLoyaltyCashback=", ", notifyNewsCall=", sbV, this.n0, this.o0);
        k5h.C(", selfExcluded=", ", passportDateExpireText=", sbV, this.p0, this.q0);
        gtg0.B(this.r0, ", slotRestrict=", ", needChange2fa=", sbV, this.s0);
        return n22.n(sbV, this.t0, ")");
    }
}
