package a;

import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.constraintlayout.widget.Group;

/* JADX INFO: loaded from: classes3.dex */
public final class tyw implements c7q0 {
    public final Group A;
    public final Group B;
    public final TextView C;
    public final TextView D;
    public final TextView E;
    public final TextView F;
    public final TextView G;
    public final TextView H;
    public final TextView I;
    public final TextView J;
    public final TextView K;
    public final TextView L;
    public final TextView M;
    public final TextView N;
    public final TextView O;
    public final TextView P;
    public final TextView Q;
    public final TextView R;
    public final TextView S;
    public final TextView T;
    public final TextView U;
    public final TextView V;
    public final TextView W;
    public final TextView X;
    public final TextView Y;
    public final TextView Z;

    /* JADX INFO: renamed from: a, reason: collision with root package name */
    public final LinearLayout f32290a;
    public final TextView a0;
    public final Group b;
    public final TextView b0;
    public final TextView c;
    public final TextView c0;
    public final TextView d;
    public final TextView d0;
    public final Group e;
    public final TextView e0;
    public final ImageView f;
    public final TextView f0;
    public final Group g;
    public final TextView g0;
    public final Group h;
    public final TextView h0;
    public final Group i;
    public final TextView i0;
    public final Group j;
    public final TextView j0;
    public final Group k;
    public final TextView k0;
    public final Group l;
    public final TextView l0;
    public final TextView m;
    public final TextView m0;
    public final ImageView n;
    public final TextView n0;
    public final LinearLayout o;
    public final TextView o0;
    public final Group p;
    public final TextView p0;
    public final ImageView q;
    public final Group q0;
    public final Group r;
    public final Group r0;
    public final Group s;
    public final Group s0;
    public final TextView t;
    public final TextView u;
    public final Group v;
    public final TextView w;
    public final TextView x;
    public final Group y;
    public final Group z;

    public tyw(LinearLayout linearLayout, Group group, TextView textView, TextView textView2, Group group2, ImageView imageView, Group group3, Group group4, Group group5, Group group6, Group group7, Group group8, TextView textView3, ImageView imageView2, LinearLayout linearLayout2, Group group9, ImageView imageView3, Group group10, Group group11, TextView textView4, TextView textView5, Group group12, TextView textView6, TextView textView7, Group group13, Group group14, Group group15, Group group16, TextView textView8, TextView textView9, TextView textView10, TextView textView11, TextView textView12, TextView textView13, TextView textView14, TextView textView15, TextView textView16, TextView textView17, TextView textView18, TextView textView19, TextView textView20, TextView textView21, TextView textView22, TextView textView23, TextView textView24, TextView textView25, TextView textView26, TextView textView27, TextView textView28, TextView textView29, TextView textView30, TextView textView31, TextView textView32, TextView textView33, TextView textView34, TextView textView35, TextView textView36, TextView textView37, TextView textView38, TextView textView39, TextView textView40, TextView textView41, TextView textView42, TextView textView43, TextView textView44, TextView textView45, TextView textView46, TextView textView47, Group group17, Group group18, Group group19, Group group20, Group group21) {
        this.f32290a = linearLayout;
        this.b = group;
        this.c = textView;
        this.d = textView2;
        this.e = group2;
        this.f = imageView;
        this.g = group3;
        this.h = group4;
        this.i = group5;
        this.j = group6;
        this.k = group7;
        this.l = group8;
        this.m = textView3;
        this.n = imageView2;
        this.o = linearLayout2;
        this.p = group9;
        this.q = imageView3;
        this.r = group10;
        this.s = group11;
        this.t = textView4;
        this.u = textView5;
        this.v = group12;
        this.w = textView6;
        this.x = textView7;
        this.y = group13;
        this.z = group14;
        this.A = group15;
        this.B = group16;
        this.C = textView8;
        this.D = textView9;
        this.E = textView10;
        this.F = textView11;
        this.G = textView12;
        this.H = textView13;
        this.I = textView14;
        this.J = textView15;
        this.K = textView16;
        this.L = textView17;
        this.M = textView18;
        this.N = textView19;
        this.O = textView20;
        this.P = textView21;
        this.Q = textView22;
        this.R = textView23;
        this.S = textView24;
        this.T = textView25;
        this.U = textView26;
        this.V = textView27;
        this.W = textView28;
        this.X = textView29;
        this.Y = textView30;
        this.Z = textView31;
        this.a0 = textView32;
        this.b0 = textView33;
        this.c0 = textView34;
        this.d0 = textView35;
        this.e0 = textView36;
        this.f0 = textView37;
        this.g0 = textView38;
        this.h0 = textView39;
        this.i0 = textView40;
        this.j0 = textView41;
        this.k0 = textView42;
        this.l0 = textView43;
        this.m0 = textView44;
        this.n0 = textView45;
        this.o0 = textView46;
        this.p0 = textView47;
        this.q0 = group17;
        this.r0 = group18;
        this.s0 = group19;
    }

    @Override // a.c7q0
    public final View getRoot() {
        return this.f32290a;
    }
}
