"""Compatibility routes for well-known Demo APK endpoints.

These paths are generated from the APK Retrofit interfaces: each entry is
the APK's actual wrapper (BaseResponse / BaseDataResponse / raw list) with
a deterministic EMPTY payload (`[]` / `{}`), reproduced ONLY locally. Nothing
here reaches, proxies or forwards to any production endpoint. Endpoints not
listed here fall through to the Demo catch-all (`{}`).
"""
from __future__ import annotations

# (path, method, body) — wire-form paths, Retrofit HTTP method, JSON body.
COMPAT_ROUTES: list[tuple[str, str, str]] = [
    ('/Account/v1/BackCallLanguages', 'GET', '{"Error": null, "Success": true, "ErrorCode": null, "Value": []}'),
    ('/Account/v1/Mb/GetUserCalls', 'GET', '{"Error": null, "Success": true, "ErrorCode": null, "Value": []}'),
    ('/ContactsConfiguratorNew/v2/contacts/html', 'GET', '{"error": null, "data": ""}'),
    ('/DayTournAuth/DayTourn/GetDayTourn', 'POST', '{"Error": null, "Success": true, "ErrorCode": null, "Value": []}'),
    ('/DayTournAuth/DayTourn/GetDayTournUser', 'POST', '{"Error": null, "Success": true, "ErrorCode": null, "Value": []}'),
    ('/FinFeed/GetInstruments_2', 'GET', '[]'),
    ('/Games/Preview/GetActionsWorkStatus', 'GET', '{"error": null, "data": []}'),
    ('/Games/Preview/GetGameWorkStatus', 'GET', '[]'),
    ('/MainFeedLine/mb/cyber/v1/champs/{cyberPagePath}', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLine/mb/cyber/v1/gamesByChamp', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLine/mb/cyber/v1/gamesBySport/{cyberPagePath}', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLine/mb/cyber/v1/topChamps/{cyberPagePath}', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLine/mb/cyber/v1/topGames/{cyberPagePath}', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLine/mb/cyber/v3/bestGames/real', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLine/mb/subscriptions/v1/games', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLine/mobile/v1/insights', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLive/mb/cyber/v1/champs/{cyberPagePath}', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLive/mb/cyber/v1/gamesByChamp', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLive/mb/cyber/v1/gamesBySport/{cyberPagePath}', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLive/mb/cyber/v1/topChamps/{cyberPagePath}', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLive/mb/cyber/v1/topGames/{cyberPagePath}', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLive/mb/cyber/v3/bestGames/real', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLive/mb/subscriptions/v1/games', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLive/mobile/v1/bestGames', 'GET', '{"error": null, "data": []}'),
    ('/RestCoreService/v1/mb/GetAllowedSports', 'GET', '{"error": null, "data": []}'),
    ('/RestCoreService/v1/mb/GetSaleTransactions', 'GET', '{"error": null, "data": []}'),
    ('/RestCoreService/v2/mb/GetTransactHistory', 'GET', '{"error": null, "data": []}'),
    ('/VerificationService/v1/Home/verificationtypes', 'GET', '{"error": null, "data": []}'),
    ('/authenticator/api/v2/registration/get-registrations', 'GET', '{"error": null, "data": []}'),
    ('/cyberImages/v1/champs', 'GET', '{"error": null, "data": []}'),
    ('/cyberstatistic/v1/matches/cs', 'GET', '{"error": null, "data": []}'),
    ('/cyberstatistic/v1/matches/dota2', 'GET', '{"error": null, "data": []}'),
    ('/cyberstatistic/v1/matches/lol', 'GET', '{"error": null, "data": []}'),
    ('/cyberstatistic/v1/matches/rainbow', 'GET', '{"error": null, "data": []}'),
    ('/cyberstatistic/v1/matches/valorant', 'GET', '{"error": null, "data": []}'),
    ('/cyberstatistic/v1/players/cs', 'GET', '{"error": null, "data": []}'),
    ('/cyberstatistic/v1/teams-lineup/cs', 'GET', '{"error": null, "data": []}'),
    ('/cyberstatistic/v1/teams-lineup/dota2', 'GET', '{"error": null, "data": []}'),
    ('/cyberstatistic/v1/teams-lineup/lol', 'GET', '{"error": null, "data": []}'),
    ('/cyberstatistic/v1/teams-lineup/rainbow', 'GET', '{"error": null, "data": []}'),
    ('/cyberstatistic/v1/teams-lineup/valorant', 'GET', '{"error": null, "data": []}'),
    ('/cyberstatistic/v1/tournaments/cs2/feed/{feedId}', 'GET', '{"error": null, "data": []}'),
    ('/cyberstatistic/v2/calendar/tournaments', 'GET', '{"error": null, "data": []}'),
    ('/Account/v1/Bonus/GetRegisterBonuses', 'GET', '{"Error": null, "Success": true, "ErrorCode": null, "Value": []}'),
    ('/Account/v1/Bonus/GetRoleplayingBonus', 'GET', '{"Error": null, "Success": true, "ErrorCode": null, "Value": []}'),
    ('/Account/v1/GetAccountRequirements', 'GET', '{"Error": null, "Success": true, "ErrorCode": null, "Value": []}'),
    ('/Account/v1/GetDocTypes', 'GET', '{"Error": null, "Success": true, "ErrorCode": null, "Value": []}'),
    ('/Account/v1/GetPasswordRequirements', 'GET', '{"Error": null, "Success": true, "ErrorCode": null, "Value": []}'),
    ('/Account/v1/Mb/GetSocials', 'GET', '{"Error": null, "Success": true, "ErrorCode": null, "Value": []}'),
    ('/Account/v1/Mb/Question/Get', 'GET', '{"Error": null, "Success": true, "ErrorCode": null, "Value": []}'),
    ('/BetAdviser/GetBetAdvice', 'POST', '{"Error": null, "Success": true, "ErrorCode": null, "Value": []}'),
    ('/ConfigAppService/v1/App/MainMenu', 'GET', '{"error": null, "data": []}'),
    ('/ConfigAppService/v1/ComApp', 'GET', '{"error": null, "data": []}'),
    ('/ConfigAppService/v1/ComApp', 'POST', '{"error": null, "data": true}'),
    ('/Games/Gambling/Mania/GetCard', 'POST', '[]'),
    ('/Limit/time/v1/AvaliableLimits', 'GET', '{"error": null, "data": []}'),
    ('/LimitService/external/v3/reasons/selfexclude', 'GET', '{"error": null, "data": []}'),
    ('/LimitService/v2/external/mobile/limits', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLine/mb/cyber/v1/gamesByGlobalChamp', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLine/mb/cyber/v1/gamesByOpp', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLine/mb/cyber/v1/gamesByOppPartner', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLine/mb/cyber/v1/topGames/{cyberPagePath}', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLine/mobile/v1/ChampsBySport', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLine/mobile/v1/TopChamps', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLine/mobile/v1/bestGames', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLine/mobile/v1/betsOnFavoriteEvents', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLine/mobile/v1/champsBySportAndCountries', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLine/mobile/v1/expressDay', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLine/mobile/v1/favorites/games', 'POST', '{"error": null, "data": []}'),
    ('/MainFeedLine/mobile/v1/favorites/gamesByTeam', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLine/mobile/v1/gamesByChamp', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLine/mobile/v1/gamesByGlobalChamp', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLine/mobile/v1/gamesForCoupon', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLine/mobile/v1/search', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLine/mobile/v1/sports', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLine/mobile/v1/stageTableWhoWins', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLine/mobile/v1/topChampsAndCountries', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLive/mb/cyber/v1/gamesByGlobalChamp', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLive/mb/cyber/v1/gamesByOpp', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLive/mb/cyber/v1/gamesByOppPartner', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLive/mb/cyber/v1/topGames/{cyberPagePath}', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLive/mb/cyber/v2/advice', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLive/mb/result/v1/gamesBySport', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLive/mb/result/v1/sports', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLive/mobile/v1/ChampsBySportAndCountries', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLive/mobile/v1/advice', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLive/mobile/v1/bestGames', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLive/mobile/v1/betsOnFavoriteEvents', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLive/mobile/v1/expressDay', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLive/mobile/v1/favorites/games', 'POST', '{"error": null, "data": []}'),
    ('/MainFeedLive/mobile/v1/favorites/gamesByTeam', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLive/mobile/v1/gamesByChamp', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLive/mobile/v1/gamesByGlobalChamp', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLive/mobile/v1/gamesForCoupon', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLive/mobile/v1/search', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLive/mobile/v1/sports', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLive/mobile/v1/tabs/games', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLive/mobile/v1/topChampsAndCountries', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLive/mobile/v2/ChampsBySport', 'GET', '{"error": null, "data": []}'),
    ('/MainFeedLive/mobile/v2/TopChamps', 'GET', '{"error": null, "data": []}'),
    ('/Main{BetType}/mobile/duel/v1/BuildDuel', 'GET', '{"error": null, "data": []}'),
    ('/Main{BetType}/mobile/duel/v1/GetAvailablePlayersForDuel', 'GET', '{"error": null, "data": []}'),
    ('/MesCore/v1/Mobile/GetMessages', 'GET', '{"error": null, "data": []}'),
    ('/MesCore/v1/PopUp/GetPopUps', 'GET', '{"error": null, "data": []}'),
    ('/MesCore/v2/Mobile/GetMessages', 'GET', '{"error": null, "data": []}'),
    ('/MobileLiveBetX/MobileUpdateCouponMulti', 'POST', '{"Error": null, "Success": true, "ErrorCode": null, "Value": []}'),
    ('/PromoServiceAuth/CoinplayCCash/LastTransactions', 'GET', '{"Error": null, "Success": true, "ErrorCode": null, "Value": []}'),
    ('/PromoServiceAuth/GoallessFootball/GetActionMatches', 'GET', '{"Error": null, "Success": true, "ErrorCode": null, "Value": []}'),
    ('/PromotionsShowcase/v1/showcase', 'GET', '{"error": null, "data": []}'),
    ('/RestCoreService/v1/Mb/AllowedCurrencies', 'GET', '{"error": null, "data": []}'),
    ('/RestCoreService/v1/Mb/GetCallTheme', 'GET', '{"error": null, "data": []}'),
    ('/RestCoreService/v1/Mb/GetNationality', 'GET', '{"error": null, "data": []}'),
    ('/RestCoreService/v1/Mb/Sports', 'GET', '{"error": null, "data": []}'),
    ('/RestCoreService/v1/Polybet/GetRulesTextsByLastVersionArray', 'GET', '{"error": null, "data": []}'),
    ('/RestCoreService/v1/mb/GetPromoShop', 'GET', '{"error": null, "data": []}'),
    ('/aggregatorfeed/v1/cybersports', 'GET', '{"error": null, "data": []}'),
    ('/aggregatorfeed/v1/cybersportsbycategory', 'GET', '{"error": null, "data": []}'),
    ('/aggregatorfeed/v1/topcyberchamps/real', 'GET', '{"error": null, "data": []}'),
    ('/alterbuilder/v1/games', 'GET', '{"error": null, "data": []}'),
    ('/alterbuilder/v2/calcEventGroups', 'POST', '{"error": null, "data": []}'),
    ('/cmsmobile/v1/banners', 'GET', '{"error": null, "data": []}'),
    ('/cmsmobile/v1/banners/categories', 'GET', '{"error": null, "data": []}'),
    ('/cyberImages/v1/champs', 'GET', '{"error": null, "data": []}'),
    ('/cyberstatistic/v1/dota-leaderboard/players', 'GET', '{"error": null, "data": []}'),
    ('/cyberstatistic/v1/dota-leaderboard/teams', 'GET', '{"error": null, "data": []}'),
    ('/cyberstatistic/v2/calendar/available-dates', 'GET', '{"error": null, "data": []}'),
    ('/cyberstatistic/v2/team/list', 'GET', '{"error": null, "data": []}'),
    ('/cyberstatistic/v2/transfers', 'GET', '{"error": null, "data": []}'),
    ('/swipe/sportswithchamps', 'GET', '{"error": null, "data": []}'),
    ('/translate/v1/mobile/GetBannerTypes', 'GET', '{"error": null, "data": []}'),
    ('/translate/v1/mobile/GetBanners', 'GET', '{"error": null, "data": []}'),
    ('/translate/v1/mobile/GetTestBanners', 'GET', '{"error": null, "data": []}'),
    ('/webapi/mobile/v1/token/auth', 'POST', '{"error": null, "data": ""}'),
]
